bazel_dep(name = "qtbridge")
local_path_override(
  module_name = "qtbridge",
  path = "../.."
)

bazel_dep(name = "apple_support", version = "2.7.0")
bazel_dep(name = "rules_cc", version = "0.2.22")
bazel_dep(name = "rules_rs", version = "0.0.96")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "bazel_skylib", version = "1.9.0", dev_dependency = True)

toolchains = use_extension("@rules_rs//rs/toolchains:module_extension.bzl", "toolchains")
toolchains.toolchain(
    edition = "2024",
    version = "1.97.0",
)
use_repo(toolchains, "default_rust_toolchains")

# This extension is optional but can help keep existing `@rules_rust` references working.
rules_rust = use_extension("@rules_rs//rs:rules_rust.bzl", "rules_rust")
use_repo(rules_rust, "rules_rust")

register_toolchains(
    "@default_rust_toolchains//:all",
)
