# Copyright (C) 2025 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only

[package]
name = "qtbridge-interfaces"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "Qt Bridge: Proxies and interfaces between Rust and Qt"

[dependencies]
cxx.workspace = true
qtbridge-type-lib = { path = "../qtbridge-type-lib", version = "0.1.5" }
qtbridge-runtime = { path = "../qtbridge-runtime", version = "0.1.5" }

[build-dependencies]
cxx-build.workspace = true
qtbridge-build-common = { path = "../qtbridge-build-common", version = "0.1.5" }
