# Copyright (C) 2025 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only

[package]
name = "qtbridge-gen-common"
version = "0.1.0"
edition.workspace = true
description = "QtBridge: Common code for macros and code generators"

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["extra-traits", "full", "visit", "visit-mut"] }
qtbridge-build-common = { path = "../qtbridge-build-common" }
