module(name = "qtbridge")

bazel_dep(name = "apple_support", version = "2.7.0")
bazel_dep(name = "rules_rs", version = "0.0.106")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "cxx.rs", version = "1.0.197")
bazel_dep(name = "rules_cc", version = "0.2.22")
bazel_dep(name = "bazel_lib", version = "3.5.0")
bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "rules_apple", version = "4.5.3", repo_name = "rules_apple")
bazel_dep(name = "llvm", version = "0.8.18")
bazel_dep(name = "rules_shell", version = "0.8.0")



toolchains = use_extension("@rules_rs//rs/toolchains:module_extension.bzl", "toolchains")
toolchains.toolchain(
    edition = "2024",
    version = "1.97.0",
)
use_repo(toolchains, "default_rust_toolchains")

# This extension is optional but can help keep existing `@rules_rust` references working.
rules_rust = use_extension("@rules_rs//rs:rules_rust.bzl", "rules_rust")
use_repo(rules_rust, "rules_rust")

register_toolchains(
    "@default_rust_toolchains//...",
    dev_dependency = True
)

crate = use_extension("@rules_rs//rs:extensions.bzl", "crate")
crate.from_cargo(
    name = "crates",
    cargo_lock = "//:Cargo.lock",
    cargo_toml = "//:Cargo.toml",
    platform_triples = [
        "aarch64-apple-darwin",
        "aarch64-pc-windows-gnullvm",
        "aarch64-unknown-linux-gnu",
        "x86_64-apple-darwin",
        "x86_64-pc-windows-gnullvm",
        "x86_64-pc-windows-gnu",
        "x86_64-unknown-linux-gnu",
    ],
)
use_repo(crate, "crates")

crate.annotation(
  crate = "cxx",
  gen_build_script = "off",
  additive_build_file = "//third_party:cxx.BUILD.bazel",
  extra_aliased_targets = {
    "core-lib":"core-lib"
  },
  deps = ["@crates//:core-lib"]
)

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
new_local_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:local.bzl", "new_local_repository")

qt = use_extension("//third_party:extension.bzl", "qt")
new_local_repository(
  name = "qtosx-arm",
  path = "/opt/homebrew/Cellar/qt/6.11.2",
  build_file = "//third_party:qtosx-arm.BUILD.bazel",
)

# qt.osx(url = "file:///Users/christianbelloni/vendored/qtosx.tar.gz")

use_repo(qt, "qtwin32-x86", "qtwin32-arm")# , "qtosx-arm")
