# Copyright (C) 2025 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only

[package]
name = "qt_ifaces"
version = "0.1.0"
edition.workspace = true
description = "Implementation of bridges between Qt item models and Rust objects"

[dependencies]
cxx.workspace = true
qt_type_lib = { path = "../qt_type_lib" }
qtbridge-runtime = { path = "../qtbridge-runtime" }

[build-dependencies]
cxx-build.workspace = true
qtbridge-build-common = { path = "../qtbridge-build-common" }
qt_type_gen = { path = "../../code_gen/qt_type_gen" }
