# Copyright (C) 2025 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only

[package]
name = "qt_meta_gen"
version = "0.1.0"
edition.workspace = true
description = "Code that is used by the implementation of 'qobject_impl' procedural macro that makes signal/slots/properties work as expected"

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
qt_gen_common = { path = "../qt_gen_common" }
