// Copyright (C) 2025 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only

use std::collections::BTreeMap;

use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use qt_gen_common::{Naming, naming};
use qt_gen_common::type_qualified_mapping::CallOrigin;
use qt_gen_common::signature_utils::{get_qualified_types_in_signature, get_arg_ident, get_qualified_args, get_qualified_return_type, is_self_mut};

use crate::InterfaceDesc;
use crate::MethodOverride;

// Info extracted by parsing impl block of some structure by procedural macro 'qobject_impl'
pub struct InterfaceImpl {
    struct_ident: syn::Ident,                    // Name of struct that implements given interface
    desc: InterfaceDesc,                         // Description of the interface
    impl_generics: syn::Generics,                // All the generics added to the implementation and their clauses
    // overridden methods
    pure_virt: BTreeMap<String, MethodOverride>, // Implementations of methods declared as pure virtual in the interface
    impl_virt: BTreeMap<String, MethodOverride>, // Overrides of methods declared as virtual but having implementation on C++ side
    origin: CallOrigin,
}

impl InterfaceImpl {
    pub fn new(struct_ident: syn::Ident, impl_generics: syn::Generics, overrides: Vec<MethodOverride>, desc: InterfaceDesc, origin: CallOrigin) -> syn::Result<Self> {

        let mut pure_virt = BTreeMap::new();
        let mut impl_virt = BTreeMap::new();

        for o in overrides {
            let cpp_name = o.get_cpp_name();
            let cpp_name_ident = syn::Ident::new(cpp_name.as_str(), o.get_cpp_name_span());
            desc.check_is_valid_virtual_override(&o.func.sig, &cpp_name_ident)?;

            let method_desc = desc.find_method_by_cpp_name(&cpp_name).unwrap();
            let dst_map = if method_desc.is_pure_virtual() {
                &mut pure_virt
            } else {
                &mut impl_virt
            };
            if dst_map.insert(cpp_name, o).is_some() {
                return Err(syn::Error::new(cpp_name_ident.span(), format!("Method '{}' was already overridden in struct", cpp_name_ident.to_string())));
            }
        }

        Ok(Self {
            struct_ident,
            impl_generics,
            desc,
            pure_virt,
            impl_virt,
            origin,
        })
    }

    pub fn get_unimplemented_pure_methods(&self) -> syn::Result<Vec<String>> {
        let unimpl = self.desc.get_methods().iter()
            .filter_map(|method| {
                if method.is_pure_virtual() {
                    let cpp_name = method.get_cpp_name();
                    if !self.pure_virt.contains_key(cpp_name) {
                        return Some(cpp_name.to_owned())
                    }
                }
                None
        }).collect();
        Ok(unimpl)
    }

    pub fn find_override_by_cpp_name(&self, cpp_name: &str) -> Option<&MethodOverride>{
        self.pure_virt.get(cpp_name)
            .or_else(||self.impl_virt.get(cpp_name))
    }

    /// Generates traits with functions that mirror the virtual functions of the C++ interface.
    /// The resulting trait is used to dispatch calls from the Rust proxy to the user-provided
    /// implementation of the interface.
    /// An example of the trait generated by this code:
    ///
    /// use qt_type_lib::{QByteArray, QHash, QModelIndex, QVariant};
    /// pub trait QAbstractListModel {
    ///     fn index(&self, row: i32, column: i32, parent: &QModelIndex) -> QModelIndex;
    ///     fn row_count(&self, parent: &QModelIndex) -> i32;
    ///     fn data(&self, index: &QModelIndex, role: i32) -> QVariant;
    ///     fn role_names(&self) -> QHash<i32, QByteArray>;
    ///     fn set_data(&mut self, index: &QModelIndex, value: &QVariant, role: i32) -> bool;
    ///     fn remove_rows(&mut self, first: i32, count: i32, parent: &QModelIndex) -> bool;
    ///     fn sibling(&self, row: i32, column: i32, idx: &QModelIndex) -> QModelIndex;
    /// }
    ///
    pub fn generate_iface_trait_impl(&self) -> syn::Result<syn::ItemImpl> {
        let iface_name = self.desc.get_ident();
        let iface_module = naming::rust::module::from_struct_name(iface_name);
        let iface_name = self.desc.get_ident();
        let struct_name = &self.struct_ident;
        let (impl_generics, type_generics, where_clause) = self.impl_generics.split_for_impl();
        let iface_library = self.origin.iface_module();

        let mut trait_impl: syn::ItemImpl = syn::parse2(quote! {
            /// Rust implementation of C++ interface methods
            impl #impl_generics #iface_library::#iface_module::#iface_name for #struct_name #type_generics #where_clause {
            }
        })?;
        trait_impl.items = self.generate_iface_trait_functions()?
            .into_iter()
            .map(syn::ImplItem::from)
            .collect();
        Ok(trait_impl)
    }

    /// Produces the list of Rust trait functions that implement the methods defined in
    /// the corresponding C++ interface.
    fn generate_iface_trait_functions(&self) -> syn::Result<Vec<syn::ImplItemFn>> {
        let mut result = Vec::new();

        let struct_name = &self.struct_ident;

        for method in self.desc.get_virtual_methods() {
            let mut method_sig = method.get_signature().clone();
            get_qualified_types_in_signature(&mut method_sig, self.origin.clone())?;
            let method_cpp_name = method.get_cpp_name();

            let method_ident = match self.find_override_by_cpp_name(&method_cpp_name) {
                Some(overridden) => &overridden.func.sig.ident,
                None => &method_sig.ident,
            };

            let arg_names = method_sig.inputs.iter()
                .skip(1)
                .map(get_arg_ident)
                .collect::<syn::Result<Vec<_>>>()?;

            result.push(syn::parse2(quote! {
                #method_sig {
                    #struct_name::#method_ident(self, #(#arg_names),*)
                }
            })?);
        }

        Ok(result)
    }

    /// Generates an `impl` block with functions that forward calls to the corresponding
    /// functions of the base C++ class.
    /// An example of generated code:
    ///
    /// impl Backend {
    ///     fn role_names(&self) -> qtbridge::QHash<i32, qtbridge::QByteArray> {
    ///         let proxy = backend_impl_details::get_rust_proxy(self);
    ///         proxy.base_role_names()
    ///     }
    ///     fn base_set_data(&mut self, index: &qtbridge::QModelIndex, value: &qtbridge::QVariant, role: i32) -> bool {
    ///         let proxy = backend_impl_details::get_rust_proxy_mut(self);
    ///         proxy.base_set_data(index, value, role)
    ///     }
    /// ...
    /// }
    ///
    pub fn generate_iface_base_impl(&self) -> syn::Result<syn::ItemImpl> {
        let struct_name = &self.struct_ident;
        let (impl_generics, type_generics, where_clause) = self.impl_generics.split_for_impl();

        let mut item_impl: syn::ItemImpl = syn::parse2(quote! {
            /// Impl block with base functions
            impl #impl_generics #struct_name #type_generics #where_clause {
            }
        })?;
        item_impl.items = self.generate_iface_base_functions()?
            .into_iter()
            .map(syn::ImplItem::from)
            .collect();
        Ok(item_impl)
    }

    /// Generates functions that forward calls to the base C++ implementation of the associated C++ interface.
    fn generate_iface_base_functions(&self) -> syn::Result<Vec<syn::ImplItemFn>> {
        let impl_detail_mod_name = naming::rust::module::impl_details(&self.struct_ident.to_string());

        let mut result = Vec::new();
        for method in self.desc.get_methods() {
            if method.is_pure_virtual() {
                continue
            }

            let method_sig = method.get_signature();
            let is_overriden = if method.is_virtual() {
                self.find_override_by_cpp_name(method.get_cpp_name())
                    .is_some()
            }
            else {
                false
            };

            result.push(Self::generate_forward_to_base_func(method_sig, &impl_detail_mod_name, &self.origin, is_overriden)?);
        }

        Ok(result)
    }

    /// Generates a function that obtains a reference to the Rust proxy and calls the
    /// corresponding method, which is then dispatched to the base implementation
    /// of the C++ interface.
    fn generate_forward_to_base_func(callee_sig: &syn::Signature, impl_detail_mod_name: &Naming, origin: &CallOrigin, add_prefix_to_caller_name: bool) -> syn::Result<syn::ImplItemFn> {
        let callee_sig_ident = &callee_sig.ident;
        let caller_name = if add_prefix_to_caller_name {
            naming::rust::function::base(&callee_sig_ident)
        }
        else {
            callee_sig_ident.into()
        };

        let inputs = get_qualified_args(callee_sig.inputs.iter(), origin.clone())?;
        let inputs_names = inputs.iter().skip(1)
            .map(get_arg_ident)
            .collect::<syn::Result<Vec<_>>>()?;
        let output = get_qualified_return_type(&callee_sig.output, origin.clone())?;
        let callee_name = naming::rust::function::base(&callee_sig_ident);

        let get_proxy = match is_self_mut(callee_sig) {
            true =>  quote! { get_rust_proxy_mut },
            false => quote! { get_rust_proxy },
        };

        let mut call = quote! {
            proxy.#callee_name(#(#inputs_names),*)
        };
        if callee_sig.unsafety.is_some() {
            call = quote! {
                unsafe { #call }
            }
        }

        let func_code = quote!{
            fn #caller_name(#(#inputs),*) #output {
                let proxy = #impl_detail_mod_name::#get_proxy(self);
                #call
            }
        };
        syn::parse2(func_code)
    }

    /// Generate implementation details that we place in a dedicated module
    /// not to clutter impl block of the given structure too much.
    pub fn generate_impl_details(&self) -> syn::Result<TokenStream> {
        let struct_ident = &self.struct_ident;
        let struct_str = struct_ident.to_string();
        let proxies_map_name = format_ident!("{}_PROXY_INSTANCES", struct_ident.to_string().to_ascii_uppercase());
        let impl_details_mod = naming::rust::module::impl_details(&struct_str);

        let iface_name = self.desc.get_ident();
        let iface_module = naming::rust::module::from_struct_name(iface_name);
        let proxy_rust = naming::rust::structure::proxy_rust(iface_name);
        let iface_traits_name = naming::rust::traits::iface_trait(iface_name);

        let (impl_generics, type_generics, where_clause) = self.impl_generics.split_for_impl();

        let iface_library = self.origin.iface_module();
        let type_library = self.origin.type_module();
        let bridge_library = self.origin.bridge_module();

        let code = quote! {
            /// Functionality called from implementation internals that makes sense to place in a separate module
            /// rather than overwhelm impl block of struct or add yet another trait impl.
            mod #impl_details_mod {
                use std::cell::{BorrowError, BorrowMutError, RefCell};
                use std::rc::Rc;

                /// Alias for the user-defined struct annotated with `#[qobject_impl]` for which this module is generated.
                type RustObj #type_generics = super::#struct_ident #type_generics;

                /// Alias for the Rust proxy type corresponding to the user-defined type.
                /// The Rust proxy is an intermediate layer between the Rust object and the C++ proxy,
                /// forwarding calls in both directions and managing borrowing of the Rust object
                /// during QAIM calls (and TBD for meta calls as well).
                pub(in super) type ProxyRust = #iface_library::#iface_module::#proxy_rust;

                /// Type alias for a map containing all instances of the given user-defined type.
                type ProxiesMap = std::collections::HashMap<*const u8, *const ProxyRust>;

                /// Shared map containing all registered instances of given user-defined type (multiton).
                thread_local!(static #proxies_map_name: std::cell::RefCell<ProxiesMap> =
                    std::cell::RefCell::new(ProxiesMap::default())
                );

                /// Invoke the provided function if immutable borrowing succeeds.
                fn try_borrow_proxies_map<F, R>(f: F) -> R
                where F: FnOnce(&ProxiesMap) -> R
                {
                    #proxies_map_name.try_with(|proxies_map_cell| -> Result<R, BorrowError> {
                        let proxies_map_ref = proxies_map_cell.try_borrow()?;
                        Ok(f(&proxies_map_ref))
                    })
                    .unwrap()
                    .expect("Failed to borrow map of proxies")
                }

                /// Invoke the provided function if mutable borrowing succeeds.
                fn try_borrow_mut_proxies_map<F, R>(f: F) -> R
                where F: FnOnce(&mut ProxiesMap) -> R
                {
                    #proxies_map_name.try_with(|proxies_map_cell| -> Result<R, BorrowMutError> {
                        let mut proxies_map_ref_mut = proxies_map_cell.try_borrow_mut()?;
                        Ok(f(&mut proxies_map_ref_mut))
                    })
                    .unwrap()
                    .expect("Failed to borrow_mut map of proxies")
                }

                /// Return an immutable reference to the Rust proxy linked to the Rust object specified in the argument.
                pub(in super) fn get_rust_proxy #impl_generics(rust_obj_ref: &RustObj #type_generics) -> &ProxyRust
                #where_clause
                {
                    get_rust_proxy_mut(rust_obj_ref)
                }

                /// Return a mutable reference to the Rust proxy linked to the Rust object specified in the argument.
                pub(in super) fn get_rust_proxy_mut #impl_generics(rust_obj_ref: &RustObj #type_generics) -> &mut ProxyRust
                #where_clause
                {
                    try_get_rust_proxy_mut(rust_obj_ref)
                        .expect("No proxy registered for given rust object")
                }

                /// Return a Result wrapping mutable reference to the Rust proxy associated with the specified object.
                pub(in super) fn try_get_rust_proxy_mut #impl_generics(rust_obj_ref: &RustObj #type_generics) -> Option<&mut ProxyRust> {
                    let ptr = try_borrow_mut_proxies_map(|proxies| {
                        let rust_obj_ptr = std::ptr::from_ref(rust_obj_ref).cast();
                        match proxies.get(&rust_obj_ptr) {
                            Some(ptr) => ptr.cast_mut(),
                            None => std::ptr::null_mut(),
                        }
                    });
                    unsafe { ptr.as_mut() }
                }

                /// Return Result with QObject linked to the Rust object provided as an argument.
                pub(crate) fn try_get_qobject #impl_generics(this: &RustObj #type_generics) -> Option<&mut #type_library::QObject>
                #where_clause
                {
                    let rust_proxy = try_get_rust_proxy_mut(this)?;
                    let cpp_proxy = rust_proxy.get_cpp_proxy();
                    let qobject_ptr: *const #type_library::QObject = cpp_proxy.cast();
                    unsafe { qobject_ptr.cast_mut().as_mut() }
                }

                /// Return QObject linked to the Rust object provided as an argument.
                pub(crate) fn get_qobject #impl_generics(this: &RustObj #type_generics) -> &mut #type_library::QObject
                #where_clause
                {
                    try_get_qobject(this)
                        .expect("QObject is not attached")
                }

                /// Register the given Rust object instance in the multiton.
                /// Create Rust and C++ proxies and links them to the Rust object.
                pub(crate) fn register_instance_in_map #impl_generics(rust_obj_rc: Rc<RefCell<RustObj #type_generics>>, register_strong: bool)
                #where_clause
                {
                    let key = (*rust_obj_rc).as_ptr() as *const u8;
                    try_borrow_mut_proxies_map(|proxies| {
                        let dyn_rc: Rc<RefCell<dyn #iface_library::#iface_module::#iface_traits_name>> = rust_obj_rc;
                        let proxy_ptr = ProxyRust::new(&dyn_rc, register_strong, unregister_instance_in_map);
                        proxies.insert(key, proxy_ptr);
                    })
                }

                /// Register the given Rust object instance in the multiton.
                /// Create Rust and C++ proxies and links them to the Rust object.
                /// C++ proxy created using placement new operator at the memory address provided as the first argument.
                pub(super) fn register_instance_in_map_with_cpp_proxy_at #impl_generics(addr: *mut u8, rust_obj_rc: Rc<RefCell<RustObj #type_generics>>)
                #where_clause
                {
                    let key = (*rust_obj_rc).as_ptr() as *const u8;
                    try_borrow_mut_proxies_map(|proxies| {
                        let dyn_rc: Rc<RefCell<dyn #iface_library::#iface_module::#iface_traits_name>> = rust_obj_rc;
                        let proxy_ptr = ProxyRust::new_with_cpp_proxy_at(addr, &dyn_rc, unregister_instance_in_map);
                        proxies.insert(key, proxy_ptr);
                    })
                }

                /// Removes the entry associated with the specified Rust object from the multiton map.
                pub(super) fn unregister_instance_in_map(rust_obj_ptr: *const u8) {
                    try_borrow_mut_proxies_map(|proxies| proxies.remove(&rust_obj_ptr))
                        .expect("Proxy object for rust object is not registered")
                        .cast_mut();
                }

                /// Configure the QObject associated with the given Rust object to use
                /// the dynamic metaobject specific to this Rust type.
                pub(crate) fn set_dynamic_meta #impl_generics(instance: &Rc<RefCell<RustObj #type_generics>>)
                #where_clause
                {
                    let dynamic_meta = <RustObj #type_generics as #bridge_library::QMetaInfo>::get_shared_dynamic_meta_object_data();
                    let instance_ref = &instance.borrow();
                    let qobject_ref = get_qobject(instance_ref);
                    dynamic_meta.set_to_qobject(qobject_ref);
                }
            }
        };
        Ok(code)
    }

    /// Generate an `impl` block with functions for attaching, detaching,
    /// and accessing the corresponding `QObject`.
    pub fn generate_qobject_funcs(&self) -> syn::Result<syn::ItemImpl> {
        let struct_name = &self.struct_ident;
        let (impl_generics, type_generics, where_clause) = self.impl_generics.split_for_impl();
        let impl_details_name = naming::rust::module::impl_details(struct_name);
        let type_library = self.origin.type_module();

        let functions_code = [
            quote! {
                /// Create a new default-initialized object of this type with a `QObject` already attached.
                /// The object must remain at its original heap location and must not be moved out of `Rc<RefCell<T>>`.
                /// TODO: rename it so that 'qobject' is not exposed to the user.
                /// TODO: or attach a qobject on demand/when sending the object to QML engine?.
                pub fn default_with_attached_qobject() -> std::rc::Rc<std::cell::RefCell<Self>> {
                    let instance = std::rc::Rc::new(std::cell::RefCell::new(Self::default()));
                    Self::attach_qobject(&instance);
                    instance
                }
            },
            quote! {
                /// Attach a dedicated `QObject` to the Rust object given as an argument.
                /// Rust object must remain at its original heap location and must not be moved out of `Rc<RefCell<T>>`.
                /// TODO: rename it so that 'qobject' is not exposed to the user.
                /// TODO: or attach a qobject on demand/when sending the object to QML engine?.
                pub fn attach_qobject(instance: &std::rc::Rc<std::cell::RefCell<Self>>) {
                    #impl_details_name::register_instance_in_map(instance.clone(), false);
                    #impl_details_name::set_dynamic_meta(instance);
                }
            },
            quote! {
                /// Detach and remove the dedicated `QObject` from the specified object.
                /// This function is intended to be called during the `Drop` of this type.
                /// TODO: Rename it so that 'qobject' is not exposed to the user.
                /// TODO: Document somewhere (in the documentation of #[qobject_impl]?) that this function must be called from the `Drop` implementation of the user-defined type.
                pub fn detach_qobject(&self) {
                    if let Some(qobj) = #impl_details_name::try_get_qobject(self) {
                        // QObject destructor will drop Rust proxy and remove entry from the instance map
                        #type_library::QObject::delete(std::ptr::from_mut(qobj));
                    }
                    // None if corresponding item was already deleted from the instance map
                }
            },
            quote! {
                /// Return a reference to the QObject attached to 'self'.
                // TODO: probably remove it later
                pub fn get_qobject(&self) -> &mut #type_library::QObject {
                    #impl_details_name::get_qobject(self)
                }
            },
            quote! {
                /// Return a QVariant containing a pointer to the QObject proxy
                /// corresponding to 'self'.
                pub fn as_qvariant(&self) -> #type_library::QVariant {
                    // TODO: handle changes in reference counter via QMetaTypeInterface
                    let qobj_ref = #impl_details_name::get_qobject(self);
                    let qobj_ptr = std::ptr::from_mut(qobj_ref);
                    qobj_ptr.into()
                }
            }
        ];
        let functions = functions_code.into_iter()
            .map(syn::parse2)
            .collect::<syn::Result<Vec<syn::ImplItemFn>>>()?;

        let mut item_impl: syn::ItemImpl = syn::parse2(quote! {
            /// Impl block with functions needed to attach, detach and reference QObject corresponding to given Rust object
            impl #impl_generics #struct_name #type_generics #where_clause {
            }
        })?;
        item_impl.items = functions.into_iter()
            .map(syn::ImplItem::from)
            .collect();

        Ok(item_impl)
    }
}
