# Copyright (C) 2025 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only

[package]
name = "qtbridge"
version = "0.1.0"
edition = "2024"
description = "Meta-package for QtBridge"

[dependencies]
qtbridge-build-common = { path = "../qtbridge-build-common"}
qtbridge-runtime = { path = "../qtbridge-runtime" }
qtbridge-gen = { path = "../qtbridge-gen" }
qtbridge-interfaces = { path = "../qtbridge-interfaces" }
qtbridge-type-lib = { path = "../qtbridge-type-lib" }
