# Copyright (C) 2025 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only

[package]
name = "qt_gen_impl"
version = "0.1.0"
edition.workspace = true
description = "Package containing implementation of procedural macros #[qobject], #[qml_element] and code generation needed to implement Qt item model on the Rust side"

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
qt_gen_common = { path = "qt_gen_common" }
qt_gen_common_no_types = { path = "qt_gen_common_no_types" }
# qt_iface_gen_lib = { path = "qt_iface_gen_lib" }
qt_meta_gen = { path = "qt_meta_gen" }

[build-dependencies]
qt_type_gen = { path = "qt_type_gen" }
