# Copyright (C) 2025 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only

[package]
name = "qtbridge-runtime"
version = "0.1.0"
edition.workspace = true
description = "QtBridge: bridging code to be run in applications."

[dependencies]
cxx.workspace = true
qtbridge-type-lib = { path = "../qtbridge-type-lib" }

[build-dependencies]
cxx-build.workspace = true
qtbridge-build-common = { path = "../qtbridge-build-common" }
qt_type_gen = { path = "../../code_gen/qt_type_gen" }

[dev-dependencies]
qtbridge = { path = "../qtbridge" }
