# Copyright (C) 2026 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only

[package]
name = "qtbridge-gen"
version = "0.1.0"
edition.workspace = true
description = "QtBridge: Generative macros for QObjects"

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
qtbridge-build-common = { path = "../qtbridge-build-common" }
qtbridge-gen-common = { path = "../qtbridge-gen-common" }
qtbridge-type-lib = { path = "../qtbridge-type-lib" }

[dev-dependencies]
pretty_assertions = "1"
insta = { version = "1", features = ["glob"] }
