[alias]
run-hello-world  = "run --manifest-path apps/hello_world/Cargo.toml"
run-host-monitor  = "run --manifest-path apps/host_monitor/Cargo.toml"
run-minimal-app = "run --manifest-path apps/minimal_app/Cargo.toml"
