load("@qtbridge//third_party:rules.bzl", "qt_resource")

qt_resource(
  name = "CustomColor",
  qrc = "res.qrc",
  srcs = ["Colors.qml"],
  qmldir = "qmldir",
  visibility = ["//visibility:public"]
)
