[package]
name = "qresource_macro"
version = "0.1.0"
edition.workspace = true
description = "Macro to make data acessible in QML"

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
qt_gen_common = { path = "../../qt_gen_common" }
build_common = { path = "../../build_common" }
