// Copyright (C) 2025 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only
// This file was auto generated by qt_type_gen package

fn get_non_generic_types() -> [QtNonGenericType; 18usize] {
    [
        QtNonGenericType::new_str("QByteArray", "core::qbytearray", MetaTypeId::Constant(12i32), ""),
        QtNonGenericType::new_str("QGuiApplication", "gui::qguiapplication", MetaTypeId::None, ""),
        QtNonGenericType::new_str("QJsonArray", "core::qjsonarray", MetaTypeId::Constant(47i32), ""),
        QtNonGenericType::new_str("QJsonObject", "core::qjsonobject", MetaTypeId::Constant(46i32), ""),
        QtNonGenericType::new_str("QJsonValue", "core::qjsonvalue", MetaTypeId::Constant(45i32), ""),
        QtNonGenericType::new_str("QMetaObject", "core::qmetaobject", MetaTypeId::None, ""),
        QtNonGenericType::new_str("QMetaType", "core::qmetatype", MetaTypeId::None, ""),
        QtNonGenericType::new_str("QMetaTypeFlag", "core::qmetatype", MetaTypeId::None, ""),
        QtNonGenericType::new_str("QMetaTypeInterface", "core::qmetatypeinterface", MetaTypeId::None, "QtPrivate"),
        QtNonGenericType::new_str("QModelIndex", "core::qmodelindex", MetaTypeId::Constant(42i32), ""),
        QtNonGenericType::new_str("QObject", "core::qobject", MetaTypeId::None, ""),
        QtNonGenericType::new_str("QQmlApplicationEngine", "qml::qqmlapplicationengine", MetaTypeId::None, ""),
        QtNonGenericType::new_str("QSignalBlocker", "core::qsignalblocker", MetaTypeId::None, ""),
        QtNonGenericType::new_str("QSignalSpy", "testlib::qsignalspy", MetaTypeId::None, ""),
        QtNonGenericType::new_str("QString", "core::qstring", MetaTypeId::Constant(10i32), ""),
        QtNonGenericType::new_str("QTranslator", "core::qtranslator", MetaTypeId::None, ""),
        QtNonGenericType::new_str("QUtf8StringView", "core::qutf8stringview", MetaTypeId::Runtime, ""),
        QtNonGenericType::new_str("QVariant", "core::qvariant", MetaTypeId::Constant(41i32), ""),
    ]
}
fn get_generic_types() -> [QtGenericTypeWithoutArgs; 3usize] {
    [
        QtGenericTypeWithoutArgs::new_str("QHash", "core::qhash", &["K", "V"]),
        QtGenericTypeWithoutArgs::new_str("QList", "core::qlist", &["T"]),
        QtGenericTypeWithoutArgs::new_str("QMap", "core::qmap", &["K", "V"]),
    ]
}
fn get_monomorphed_types() -> [QtMonomorphedType; 22usize] {
    [
        QtMonomorphedType::new_str(
            "QHash_QByteArray_QVariant",
            "core::qhash",
            QtGenericTypeWithoutArgs::find_by_name("QHash")
                .unwrap()
                .set_args(vec!["QByteArray".try_into().unwrap(), "QVariant".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::None,
        ),
        QtMonomorphedType::new_str(
            "QHash_QString_QVariant",
            "core::qhash",
            QtGenericTypeWithoutArgs::find_by_name("QHash")
                .unwrap()
                .set_args(vec!["QString".try_into().unwrap(), "QVariant".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::Constant(28i32),
        ),
        QtMonomorphedType::new_str(
            "QHash_i32_QByteArray",
            "core::qhash",
            QtGenericTypeWithoutArgs::find_by_name("QHash")
                .unwrap()
                .set_args(vec!["i32".try_into().unwrap(), "QByteArray".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::None,
        ),
        QtMonomorphedType::new_str(
            "QList_QByteArray",
            "core::qlist",
            QtGenericTypeWithoutArgs::find_by_name("QList")
                .unwrap()
                .set_args(vec!["QByteArray".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::Constant(49i32),
        ),
        QtMonomorphedType::new_str(
            "QList_QString",
            "core::qlist",
            QtGenericTypeWithoutArgs::find_by_name("QList")
                .unwrap()
                .set_args(vec!["QString".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::Constant(11i32),
        ),
        QtMonomorphedType::new_str(
            "QList_QVariant",
            "core::qlist",
            QtGenericTypeWithoutArgs::find_by_name("QList")
                .unwrap()
                .set_args(vec!["QVariant".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::Constant(9i32),
        ),
        QtMonomorphedType::new_str(
            "QList_bool",
            "core::qlist",
            QtGenericTypeWithoutArgs::find_by_name("QList")
                .unwrap()
                .set_args(vec!["bool".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::Runtime,
        ),
        QtMonomorphedType::new_str(
            "QList_f32",
            "core::qlist",
            QtGenericTypeWithoutArgs::find_by_name("QList")
                .unwrap()
                .set_args(vec!["f32".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::Runtime,
        ),
        QtMonomorphedType::new_str(
            "QList_f64",
            "core::qlist",
            QtGenericTypeWithoutArgs::find_by_name("QList")
                .unwrap()
                .set_args(vec!["f64".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::Runtime,
        ),
        QtMonomorphedType::new_str(
            "QList_i16",
            "core::qlist",
            QtGenericTypeWithoutArgs::find_by_name("QList")
                .unwrap()
                .set_args(vec!["i16".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::Runtime,
        ),
        QtMonomorphedType::new_str(
            "QList_i32",
            "core::qlist",
            QtGenericTypeWithoutArgs::find_by_name("QList")
                .unwrap()
                .set_args(vec!["i32".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::Runtime,
        ),
        QtMonomorphedType::new_str(
            "QList_i64",
            "core::qlist",
            QtGenericTypeWithoutArgs::find_by_name("QList")
                .unwrap()
                .set_args(vec!["i64".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::Runtime,
        ),
        QtMonomorphedType::new_str(
            "QList_i8",
            "core::qlist",
            QtGenericTypeWithoutArgs::find_by_name("QList")
                .unwrap()
                .set_args(vec!["i8".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::Runtime,
        ),
        QtMonomorphedType::new_str(
            "QList_isize",
            "core::qlist",
            QtGenericTypeWithoutArgs::find_by_name("QList")
                .unwrap()
                .set_args(vec!["isize".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::Runtime,
        ),
        QtMonomorphedType::new_str(
            "QList_ptr_mut_QObject",
            "core::qlist",
            QtGenericTypeWithoutArgs::find_by_name("QList")
                .unwrap()
                .set_args(vec!["*mut QObject".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::Runtime,
        ),
        QtMonomorphedType::new_str(
            "QList_u16",
            "core::qlist",
            QtGenericTypeWithoutArgs::find_by_name("QList")
                .unwrap()
                .set_args(vec!["u16".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::Runtime,
        ),
        QtMonomorphedType::new_str(
            "QList_u32",
            "core::qlist",
            QtGenericTypeWithoutArgs::find_by_name("QList")
                .unwrap()
                .set_args(vec!["u32".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::Runtime,
        ),
        QtMonomorphedType::new_str(
            "QList_u64",
            "core::qlist",
            QtGenericTypeWithoutArgs::find_by_name("QList")
                .unwrap()
                .set_args(vec!["u64".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::Runtime,
        ),
        QtMonomorphedType::new_str(
            "QList_u8",
            "core::qlist",
            QtGenericTypeWithoutArgs::find_by_name("QList")
                .unwrap()
                .set_args(vec!["u8".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::Runtime,
        ),
        QtMonomorphedType::new_str(
            "QList_usize",
            "core::qlist",
            QtGenericTypeWithoutArgs::find_by_name("QList")
                .unwrap()
                .set_args(vec!["usize".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::Runtime,
        ),
        QtMonomorphedType::new_str(
            "QMap_QString_QVariant",
            "core::qmap",
            QtGenericTypeWithoutArgs::find_by_name("QMap")
                .unwrap()
                .set_args(vec!["QString".try_into().unwrap(), "QVariant".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::Constant(8i32),
        ),
        QtMonomorphedType::new_str(
            "QMap_i32_QString",
            "core::qmap",
            QtGenericTypeWithoutArgs::find_by_name("QMap")
                .unwrap()
                .set_args(vec!["i32".try_into().unwrap(), "QString".try_into().unwrap()])
                .unwrap(),
            MetaTypeId::None,
        ),
    ]
}
fn get_alias_to_monomorphed_types() -> [QtAliasToMonomorphedType; 6usize] {
    [
        QtAliasToMonomorphedType::new_str("QByteArrayList", "QList_QByteArray", "core::qlist", MetaTypeId::Constant(49i32)),
        QtAliasToMonomorphedType::new_str("QObjectList", "QList_ptr_mut_QObject", "core::qlist", MetaTypeId::Runtime),
        QtAliasToMonomorphedType::new_str("QStringList", "QList_QString", "core::qlist", MetaTypeId::Constant(11i32)),
        QtAliasToMonomorphedType::new_str("QVariantHash", "QHash_QString_QVariant", "core::qhash", MetaTypeId::Constant(28i32)),
        QtAliasToMonomorphedType::new_str("QVariantList", "QList_QVariant", "core::qlist", MetaTypeId::Constant(9i32)),
        QtAliasToMonomorphedType::new_str("QVariantMap", "QMap_QString_QVariant", "core::qmap", MetaTypeId::Constant(8i32)),
    ]
}
