// Copyright (C) 2025 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only
// This file was auto generated by qt_type_gen package

fn get_non_generic_types() -> [QtNonGenericType; 14usize] {
    [
        QtNonGenericType::new_str("QByteArray", "core::qbytearray", MetaTypeId::Constant(12i32), ""),
        QtNonGenericType::new_str("QGuiApplication", "gui::qguiapplication", MetaTypeId::None, ""),
        QtNonGenericType::new_str("QMetaObject", "core::qmetaobject", MetaTypeId::None, ""),
        QtNonGenericType::new_str("QMetaType", "core::qmetatype", MetaTypeId::None, ""),
        QtNonGenericType::new_str("QMetaTypeFlag", "core::qmetatype", MetaTypeId::None, ""),
        QtNonGenericType::new_str("QMetaTypeInterface", "core::qmetatypeinterface", MetaTypeId::None, "QtPrivate"),
        QtNonGenericType::new_str("QModelIndex", "core::qmodelindex", MetaTypeId::Constant(42i32), ""),
        QtNonGenericType::new_str("QObject", "core::qobject", MetaTypeId::None, ""),
        QtNonGenericType::new_str("QQmlApplicationEngine", "qml::qqmlapplicationengine", MetaTypeId::None, ""),
        QtNonGenericType::new_str("QSignalBlocker", "core::qsignalblocker", MetaTypeId::None, ""),
        QtNonGenericType::new_str("QSignalSpy", "testlib::qsignalspy", MetaTypeId::None, ""),
        QtNonGenericType::new_str("QString", "core::qstring", MetaTypeId::Constant(10i32), ""),
        QtNonGenericType::new_str("QUtf8StringView", "core::qutf8stringview", MetaTypeId::Runtime, ""),
        QtNonGenericType::new_str("QVariant", "core::qvariant", MetaTypeId::Constant(41i32), ""),
    ]
}
fn get_generic_types() -> [QtGenericTypeWithoutArgs; 3usize] {
    [
        QtGenericTypeWithoutArgs::new_str("QHash", "core::qhash", &["K", "V"]),
        QtGenericTypeWithoutArgs::new_str("QList", "core::qlist", &["T"]),
        QtGenericTypeWithoutArgs::new_str("QMap", "core::qmap", &["K", "V"]),
    ]
}
fn get_monomorphed_types(generics: &[QtGenericTypeWithoutArgs], non_generics: &[QtNonGenericType]) -> [QtMonomorphedType; 21usize] {
    [
        QtMonomorphedType::new_str(
            "QHash_QByteArray_QVariant",
            "core::qhash",
            generics
                .iter()
                .find(|generic| generic.name() == "QHash")
                .unwrap()
                .set_args(vec![
                    non_generics.iter().find(|non_gen| non_gen.name() == "QByteArray").unwrap().clone().into(),
                    non_generics.iter().find(|non_gen| non_gen.name() == "QVariant").unwrap().clone().into(),
                ])
                .unwrap(),
            MetaTypeId::None,
        ),
        QtMonomorphedType::new_str(
            "QHash_QString_QVariant",
            "core::qhash",
            generics
                .iter()
                .find(|generic| generic.name() == "QHash")
                .unwrap()
                .set_args(vec![
                    non_generics.iter().find(|non_gen| non_gen.name() == "QString").unwrap().clone().into(),
                    non_generics.iter().find(|non_gen| non_gen.name() == "QVariant").unwrap().clone().into(),
                ])
                .unwrap(),
            MetaTypeId::Constant(28i32),
        ),
        QtMonomorphedType::new_str(
            "QHash_i32_QByteArray",
            "core::qhash",
            generics
                .iter()
                .find(|generic| generic.name() == "QHash")
                .unwrap()
                .set_args(vec![
                    PrimitiveType::find_by_name("i32").unwrap().clone().into(),
                    non_generics.iter().find(|non_gen| non_gen.name() == "QByteArray").unwrap().clone().into(),
                ])
                .unwrap(),
            MetaTypeId::None,
        ),
        QtMonomorphedType::new_str(
            "QList_QByteArray",
            "core::qlist",
            generics
                .iter()
                .find(|generic| generic.name() == "QList")
                .unwrap()
                .set_args(vec![non_generics.iter().find(|non_gen| non_gen.name() == "QByteArray").unwrap().clone().into()])
                .unwrap(),
            MetaTypeId::Constant(49i32),
        ),
        QtMonomorphedType::new_str(
            "QList_QString",
            "core::qlist",
            generics
                .iter()
                .find(|generic| generic.name() == "QList")
                .unwrap()
                .set_args(vec![non_generics.iter().find(|non_gen| non_gen.name() == "QString").unwrap().clone().into()])
                .unwrap(),
            MetaTypeId::Constant(11i32),
        ),
        QtMonomorphedType::new_str(
            "QList_QVariant",
            "core::qlist",
            generics
                .iter()
                .find(|generic| generic.name() == "QList")
                .unwrap()
                .set_args(vec![non_generics.iter().find(|non_gen| non_gen.name() == "QVariant").unwrap().clone().into()])
                .unwrap(),
            MetaTypeId::Constant(9i32),
        ),
        QtMonomorphedType::new_str(
            "QList_bool",
            "core::qlist",
            generics
                .iter()
                .find(|generic| generic.name() == "QList")
                .unwrap()
                .set_args(vec![PrimitiveType::find_by_name("bool").unwrap().clone().into()])
                .unwrap(),
            MetaTypeId::None,
        ),
        QtMonomorphedType::new_str(
            "QList_f32",
            "core::qlist",
            generics
                .iter()
                .find(|generic| generic.name() == "QList")
                .unwrap()
                .set_args(vec![PrimitiveType::find_by_name("f32").unwrap().clone().into()])
                .unwrap(),
            MetaTypeId::None,
        ),
        QtMonomorphedType::new_str(
            "QList_f64",
            "core::qlist",
            generics
                .iter()
                .find(|generic| generic.name() == "QList")
                .unwrap()
                .set_args(vec![PrimitiveType::find_by_name("f64").unwrap().clone().into()])
                .unwrap(),
            MetaTypeId::None,
        ),
        QtMonomorphedType::new_str(
            "QList_i16",
            "core::qlist",
            generics
                .iter()
                .find(|generic| generic.name() == "QList")
                .unwrap()
                .set_args(vec![PrimitiveType::find_by_name("i16").unwrap().clone().into()])
                .unwrap(),
            MetaTypeId::None,
        ),
        QtMonomorphedType::new_str(
            "QList_i32",
            "core::qlist",
            generics
                .iter()
                .find(|generic| generic.name() == "QList")
                .unwrap()
                .set_args(vec![PrimitiveType::find_by_name("i32").unwrap().clone().into()])
                .unwrap(),
            MetaTypeId::None,
        ),
        QtMonomorphedType::new_str(
            "QList_i64",
            "core::qlist",
            generics
                .iter()
                .find(|generic| generic.name() == "QList")
                .unwrap()
                .set_args(vec![PrimitiveType::find_by_name("i64").unwrap().clone().into()])
                .unwrap(),
            MetaTypeId::None,
        ),
        QtMonomorphedType::new_str(
            "QList_i8",
            "core::qlist",
            generics
                .iter()
                .find(|generic| generic.name() == "QList")
                .unwrap()
                .set_args(vec![PrimitiveType::find_by_name("i8").unwrap().clone().into()])
                .unwrap(),
            MetaTypeId::None,
        ),
        QtMonomorphedType::new_str(
            "QList_isize",
            "core::qlist",
            generics
                .iter()
                .find(|generic| generic.name() == "QList")
                .unwrap()
                .set_args(vec![PrimitiveType::find_by_name("isize").unwrap().clone().into()])
                .unwrap(),
            MetaTypeId::None,
        ),
        QtMonomorphedType::new_str(
            "QList_u16",
            "core::qlist",
            generics
                .iter()
                .find(|generic| generic.name() == "QList")
                .unwrap()
                .set_args(vec![PrimitiveType::find_by_name("u16").unwrap().clone().into()])
                .unwrap(),
            MetaTypeId::None,
        ),
        QtMonomorphedType::new_str(
            "QList_u32",
            "core::qlist",
            generics
                .iter()
                .find(|generic| generic.name() == "QList")
                .unwrap()
                .set_args(vec![PrimitiveType::find_by_name("u32").unwrap().clone().into()])
                .unwrap(),
            MetaTypeId::None,
        ),
        QtMonomorphedType::new_str(
            "QList_u64",
            "core::qlist",
            generics
                .iter()
                .find(|generic| generic.name() == "QList")
                .unwrap()
                .set_args(vec![PrimitiveType::find_by_name("u64").unwrap().clone().into()])
                .unwrap(),
            MetaTypeId::None,
        ),
        QtMonomorphedType::new_str(
            "QList_u8",
            "core::qlist",
            generics
                .iter()
                .find(|generic| generic.name() == "QList")
                .unwrap()
                .set_args(vec![PrimitiveType::find_by_name("u8").unwrap().clone().into()])
                .unwrap(),
            MetaTypeId::None,
        ),
        QtMonomorphedType::new_str(
            "QList_usize",
            "core::qlist",
            generics
                .iter()
                .find(|generic| generic.name() == "QList")
                .unwrap()
                .set_args(vec![PrimitiveType::find_by_name("usize").unwrap().clone().into()])
                .unwrap(),
            MetaTypeId::None,
        ),
        QtMonomorphedType::new_str(
            "QMap_QString_QVariant",
            "core::qmap",
            generics
                .iter()
                .find(|generic| generic.name() == "QMap")
                .unwrap()
                .set_args(vec![
                    non_generics.iter().find(|non_gen| non_gen.name() == "QString").unwrap().clone().into(),
                    non_generics.iter().find(|non_gen| non_gen.name() == "QVariant").unwrap().clone().into(),
                ])
                .unwrap(),
            MetaTypeId::Constant(8i32),
        ),
        QtMonomorphedType::new_str(
            "QMap_i32_QString",
            "core::qmap",
            generics
                .iter()
                .find(|generic| generic.name() == "QMap")
                .unwrap()
                .set_args(vec![
                    PrimitiveType::find_by_name("i32").unwrap().clone().into(),
                    non_generics.iter().find(|non_gen| non_gen.name() == "QString").unwrap().clone().into(),
                ])
                .unwrap(),
            MetaTypeId::None,
        ),
    ]
}
fn get_alias_to_monomorphed_types() -> [QtAliasToMonomorphedType; 5usize] {
    [
        QtAliasToMonomorphedType::new_str("QByteArrayList", "QList_QByteArray", "core::qlist", MetaTypeId::Constant(49i32)),
        QtAliasToMonomorphedType::new_str("QStringList", "QList_QString", "core::qlist", MetaTypeId::Constant(11i32)),
        QtAliasToMonomorphedType::new_str("QVariantHash", "QHash_QString_QVariant", "core::qhash", MetaTypeId::Constant(28i32)),
        QtAliasToMonomorphedType::new_str("QVariantList", "QList_QVariant", "core::qlist", MetaTypeId::Constant(9i32)),
        QtAliasToMonomorphedType::new_str("QVariantMap", "QMap_QString_QVariant", "core::qmap", MetaTypeId::Constant(8i32)),
    ]
}
